;==========================================================
;   Polybar Config - Catppuccin Mocha (Desktop)
;==========================================================

include-file = ~/.config/polybar/themes/mocha.ini

[bar/main]
width = 100%
height = 20pt
radius = 7
cursor-click = pointer

background = ${colors.base}
foreground = ${colors.text}

font-0 = "JetBrainsMono Nerd Font:weight=bold:size=12"
font-1 = "Symbols Nerd Font Mono:size=14"

line-size = 4pt

border-size = 2pt
border-color = ${colors.surface0}

padding-left = 1
padding-right = 1

module-margin = 0

modules-left = arch space date
modules-center = xworkspaces
modules-right =  cava space pulseaudio space separator space wlan space

offset-y = 3

override-redirect = true
wm-restack = i3

enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = 
label-active-padding = 1
label-active-foreground = ${colors.mauve}
label-active-font = 1

label-occupied = 
label-occupied-padding = 1
label-occupied-font = 1
label-occupied-foreground = ${colors.overlay1}

label-empty = 
label-empty-padding = 1
label-empty-font = 1
label-empty-foreground = ${colors.overlay0}


[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%


[network-base]
type = internal/network
interval = 5
format-disconnected = <label-disconnected>
label-disconnected = %{F${colors.red}}%ifname%%{F${colors.overlay1}} disconnected


[module/wlan]
#inherit = network-base
type = internal/network
inteface= wlan0
interface-type = wireless
interval = 1
click-left = /home/saptak/.config/rofi/wifi-menu.sh

format-connected = <label-connected>
label-connected = 󰖩
label-connected-foreground = ${colors.text}

format-disconnected = <label-disconnected>
label-disconnected = 󰖪
label-disconnected-foreground = ${colors.text}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = ${colors.text}
format-volume = <label-volume>

label-volume = %percentage%%
label-volume-foreground = ${colors.text}

label-muted = 󰖁 %percentage%%
label-muted-foreground = ${colors.overlay1}


[module/date]
type = internal/date
interval = 1
date = %I:%M %p | %d-%m
label = %date%
label-foreground = ${colors.text}

[module/arch]
type = custom/text
format = 󰣇
format-foreground = ${colors.lavender}


[module/space]
type = custom/text
format = " "


[module/separator]
type = custom/text
format = "|"
format-foreground = ${colors.overlay1}

[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/polybar/cava.sh
format = <label>
format-font = 5
label = %output%
label-foreground = #f9e2af
