conky.config = {
    alignment = 'top_left',
    gap_x = 10,
    gap_y = 60,
    background = true,
    double_buffer = true,
    update_interval = 1,

    own_window = true,
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    minimum_width = 250,
    maximum_width = 250,

    use_xft = true,
    font = 'storopia:size=15',

    default_color = '#cdd6f4',
};

conky.text = [[
${color cba6f7}SYSTEM
${color}CPU: ${cpu}% ${cpubar 9,120}
RAM: ${memperc}% ${membar 9,120}

${color cba6f7}DISK
${color}${fs_used /}/${fs_size /} ${fs_bar 8 /}

${color cba6f7}UPTIME
${color}${uptime}

${color cba6f7}DATE
${color}${time %A}
${time %d %B %Y}
${time %H:%M:%S}
]];
