backend = "xrender";
vsync = true;

corner-radius = 10;

# Enable blur
#blur-background = true;

# Use the convolution blur method
#blur-method = "convolution";

# Define the blur strength (kernel)
# This is a basic 3x3 Gaussian-like kernel
#blur-convolution = "3x3,1,1,1,1,1,1,1,1,1";

#backend = "glx";
#blur: {
# method = "dual_kawase";
#strength = 5;
#};
